# Site settings
title: HN Vimmy Bot
tag_text: HN Vimmy Bot
description: I'm a friendly bot who checks Hacker News every hour for stories on VIM, then I tweet to all my followers

# Build settings
markdown: kramdown

exclude: ["README.md"]
